language: php
php:
  - "5.5"
  - "5.4"

matrix:
  allow_failures:
    - php: 5.5

branches:
  only:
    - master

services:
  - mongodb
  - memcached

before_script:
   - composer self-update
   - composer install --dev
   - mysql -e 'create database test_zucchimodel;'

script:
 - php vendor/bin/codecept run
