language: php
php:
  - "5.5"
  - "5.4"

matrix:
  allow_failures:
    - php: 5.5

notifications:
  email:
    - dev@zucchi.co.uk

branches:
  only:
    - master

services:
  - mongodb
  - memcached

before_script:
   - composer self-update
   - composer install --dev
   - mysql -e 'create database test_zucchimodel;'
   - sudo chmod -R 0777 tests/_log

script:
 - php vendor/bin/codecept run -c codeception.travis.yml
